function HowItWorks() {
  const steps = [
    {
      number: "01",
      title: "Upload Resume",
      description:
        "Upload your resume and let AI analyze your strengths, weaknesses, and ATS score.",
    },
    {
      number: "02",
      title: "Practice Interviews",
      description:
        "Answer technical and HR interview questions generated by AI based on your profile.",
    },
    {
      number: "03",
      title: "Receive Feedback",
      description:
        "Get instant AI feedback with scores, improvement tips, and personalized learning recommendations.",
    },
  ];

  return (
    <section className="bg-slate-900 text-white py-24">
      <div className="max-w-7xl mx-auto px-6">

        <div className="text-center">
          <h2 className="text-4xl font-bold">
            How It Works
          </h2>

          <p className="text-gray-400 mt-4">
            Prepare for interviews in three simple steps.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-10 mt-16">
          {steps.map((step) => (
            <div
              key={step.number}
              className="bg-slate-800 rounded-2xl p-8 text-center border border-slate-700 hover:border-blue-500 transition duration-300"
            >
              <div className="w-16 h-16 rounded-full bg-blue-600 flex items-center justify-center text-2xl font-bold mx-auto mb-6">
                {step.number}
              </div>

              <h3 className="text-2xl font-semibold mb-4">
                {step.title}
              </h3>

              <p className="text-gray-400">
                {step.description}
              </p>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}

export default HowItWorks;